Repository bridge0813/bridge-ios, pull requests merged in 2023-12, with the labels that each got.

#105 마이페이지(홈) 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Profile/ProfilePreviewResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/User/ProfilePreviewResponseDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Auth/AuthEndpoint.swift
  Bridge/Sources/Data/Network/Endpoint/User/UserEndpoint.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Data/Repositories/Auth/MockAuthRepository.swift
  Bridge/Sources/Data/Repositories/User/DefaultUserRepository.swift
  Bridge/Sources/Data/Repositories/User/MockUserRepository.swift
  Bridge/Sources/Domain/Entities/Profile/ProfilePreview.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Auth/AuthRepository.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Profile/UserRepository.swift
  Bridge/Sources/Domain/UseCases/Auth/SignOutUseCase.swift
  Bridge/Sources/Domain/UseCases/Auth/SignUpUseCase.swift
  Bridge/Sources/Domain/UseCases/Auth/WithdrawUseCase.swift
  Bridge/Sources/Domain/UseCases/User/FetchProfilePreviewUseCase.swift
  Bridge/Sources/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Bridge/Sources/Presentation/Auth/SignUp/SetFieldViewController.swift
  Bridge/Sources/Presentation/Auth/SignUp/SetFieldViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/ChannelList/ChannelListViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/MyPage/Coordinator/MyPageCoordinator.swift
  Bridge/Sources/Presentation/Tab/MyPage/Home/MenuCell.swift
  Bridge/Sources/Presentation/Tab/MyPage/Home/MyPageViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Home/MyPageViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Home/ProfileHeaderView.swift
Labels: feat, design

#104 관리 탭 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/App/Coordinator/Coordinator.swift
  Bridge/Sources/Data/Network/DTOs/Chat/CreateChannelResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Profile/ApplicantProfileResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/AppliedProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/ApplyProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/User/ApplicantProfileResponseDTO.swift
  Bridge/Sources/Data/Repositories/Chat/Channel/DefaultChannelRepository.swift
  Bridge/Sources/Data/Repositories/Chat/Channel/MockChannelRepository.swift
  Bridge/Sources/Data/Repositories/Project/DefaultProjectRepository.swift
  Bridge/Sources/Data/Repositories/Project/MockProjectRepository.swift
  Bridge/Sources/Data/Repositories/User/DefaultUserRepository.swift
  Bridge/Sources/Data/Repositories/User/MockUserRepository.swift
  Bridge/Sources/Domain/Entities/Profile/ApplicantProfile.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Chat/ChannelRepository.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Profile/UserRepository.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Project/ProjectRepository.swift
  Bridge/Sources/Domain/UseCases/Chat/Channel/CreateChannelUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Accept/AcceptApplicantUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Cancel/CancelApplicationUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Delete/DeleteProjectUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/List/FetchAppliedProjectsUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Reject/RejectApplicantUseCase.swift
  Bridge/Sources/Domain/UseCases/User/FetchApplicantListUseCase.swift
  Bridge/Sources/Domain/UseCases/User/FetchProfilePreviewUseCase.swift
  Bridge/Sources/Presentation/Common/Typealias/Typealias.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Alert/AlertConfiguration.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ButtonGroup/BridgeMediumButtonGroup.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ButtonGroup/BridgeSmallButtonGroup.swift
  Bridge/Sources/Presentation/DesignSystem/Component/PopUp/Menu/BridgeActionSheet.swift
  Bridge/Sources/Presentation/DesignSystem/Component/PopUp/Menu/BridgeActionSheetButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Views/BridgePlaceholderView.swift
  Bridge/Sources/Presentation/Tab/Chat/Channel/ChannelViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
  Bridge/Sources/Presentation/Tab/Coordinator/TabBarCoordinator.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/ApplicantListViewController.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/ApplicantListViewModel.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/Cell/ApplicantCell.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/HeaderView/ApplicantNumberHeaderView.swift
  Bridge/Sources/Presentation/Tab/Management/Coordinator/ManagementCoordinator.swift
  Bridge/Sources/Presentation/Tab/Management/Management/Cell/ManagementProjectCell.swift
  Bridge/Sources/Presentation/Tab/Management/Management/HeaderView/ManagementHeaderView.swift
  Bridge/Sources/Presentation/Tab/Management/Management/ManagementTabButton.swift
  Bridge/Sources/Presentation/Tab/Management/Management/ManagementViewController.swift
  Bridge/Sources/Presentation/Tab/Management/Management/ManagementViewModel.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/Coordinator/ProjectDetailCoordinator.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailViewController.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailViewModel.swift
Labels: feat, design

#108 '모집글 상세' 네트워킹 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Resources/Assets.xcassets/Fields/field_ios.imageset/icon_ios.png
  Bridge/Sources/Data/Network/DTOs/Auth/SignIn/SignInWithAppleRequestDTO.swift
  Bridge/Sources/Data/Network/DTOs/Auth/SignIn/SignInWithAppleResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Extensions/String+DateFormat.swift
  Bridge/Sources/Data/Network/DTOs/Project/Bookmark/BookmarkRequestDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/Create/CreateProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/Detail/ProjectDetailDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/AppliedProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/DeadlineProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/HotProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/MyProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/ProjectPreviewResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/ProjectID/ProjectIDDTO.swift
  Bridge/Sources/Data/Network/DTOs/User/UserID/UserIDDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Project/ProjectEndpoint.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Data/Repositories/Project/DefaultProjectRepository.swift
  Bridge/Sources/Data/Repositories/Project/MockProjectRepository.swift
  Bridge/Sources/Data/TokenStorage/Keychain/KeychainAccount.swift
  Bridge/Sources/Data/TokenStorage/TokenStorage.swift
  Bridge/Sources/Domain/Entities/Project/Project.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Project/ProjectRepository.swift
  Bridge/Sources/Domain/UseCases/Project/Apply/ApplyProjectUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Close/CloseProjectUseCase.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/BridgeBookmarkButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/PopUp/ActionSheet/BridgeActionSheet.swift
  Bridge/Sources/Presentation/DesignSystem/Component/PopUp/ActionSheet/BridgeActionSheetButton.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Management/Coordinator/ManagementCoordinator.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/Coordinator/ProjectDetailCoordinator.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailHeaderView.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailMenuBar.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailViewController.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/ProjectDetailViewModel.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldCell.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldDetail/RecruitFieldDetailCell.swift
Labels: feat

#111 '모집글 작성' 버그 수정
  Bridge/Sources/Data/Repositories/Project/DefaultProjectRepository.swift
  Bridge/Sources/Domain/Entities/TechStack/TechStack.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/CreateProjectCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/Completion/CompletionViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberDetailInput/MemberRequirementInputViewModel.swift
Labels: feat, fix

#113 'Main' API 수정사항 반영
  Bridge/Sources/Data/Network/DTOs/User/ProfilePreviewResponseDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Project/ProjectEndpoint.swift
  Bridge/Sources/Data/Repositories/Project/DefaultProjectRepository.swift
  Bridge/Sources/Domain/UseCases/Auth/SignUpUseCase.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Views/BridgeSetFieldView.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/CreateProjectCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberDetailInput/MemberRequirementInputViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewModel.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldCell.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldDetail/RecruitFieldDetailCell.swift
Labels: feat

#114 마이페이지(알림) 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Alert/BridgeAlertResponseDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Alert/AlertEndpoint.swift
  Bridge/Sources/Data/Repositories/Alert/DefaultAlertRepository.swift
  Bridge/Sources/Data/Repositories/Alert/MockAlertRepository.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Domain/Entities/Alert/BridgeAlert.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Alert/AlertRepository.swift
  Bridge/Sources/Domain/UseCases/Alert/FetchAlertsUseCase.swift
  Bridge/Sources/Domain/UseCases/Alert/RemoveAlertUseCase.swift
  Bridge/Sources/Presentation/Tab/MyPage/Coordinator/MyPageCoordinator.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Alert/AlertCell.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Alert/AlertViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Alert/AlertViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Bookmark/BookmarkedProjectViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Bookmark/BookmarkedProjectViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Field/MyFieldViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Field/MyFieldViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Profile/ProfileViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Profile/ProfileViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Home/MyPageViewModel.swift
Labels: feat, design

#117 마이페이지(관심 분야, 북마크) 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Alert/BridgeAlertResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/User/BookmarkedProjectResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/User/ChangeFieldRequestDTO.swift
  Bridge/Sources/Data/Network/Endpoint/User/UserEndpoint.swift
  Bridge/Sources/Data/Repositories/User/DefaultUserRepository.swift
  Bridge/Sources/Data/Repositories/User/MockUserRepository.swift
  Bridge/Sources/Domain/Entities/User/BookmarkedProject.swift
  Bridge/Sources/Domain/RepositoryInterfaces/User/UserRepository.swift
  Bridge/Sources/Domain/UseCases/User/ChangeFieldUseCase.swift
  Bridge/Sources/Domain/UseCases/User/FetchBookmarkedProjectsUseCase.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Alert/AlertConfiguration.swift
  Bridge/Sources/Presentation/Tab/MyPage/Coordinator/MyPageCoordinator.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Bookmark/BookmarkedProjectCell.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Bookmark/BookmarkedProjectViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Bookmark/BookmarkedProjectViewModel.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Field/MyFieldViewController.swift
  Bridge/Sources/Presentation/Tab/MyPage/Detail/Field/MyFieldViewModel.swift
Labels: feat, design

#118 '관리' 네트워킹 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Bridge/Sources/Data/Network/DTOs/Chat/CreateChannelRequestDTO.swift
  Bridge/Sources/Data/Network/DTOs/Chat/CreateChannelResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/Applicant/ApplicantProfileResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Project/List/MyProjectResponseDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Chat/ChannelEndpoint.swift
  Bridge/Sources/Data/Network/Endpoint/Project/Applicant/ApplicantEndpoint.swift
  Bridge/Sources/Data/Network/Endpoint/Project/ProjectEndpoint.swift
  Bridge/Sources/Data/Repositories/Chat/Channel/DefaultChannelRepository.swift
  Bridge/Sources/Data/Repositories/Project/Applicant/DefaultApplicantRepository.swift
  Bridge/Sources/Data/Repositories/Project/Applicant/MockApplicantRepository.swift
  Bridge/Sources/Data/Repositories/Project/DefaultProjectRepository.swift
  Bridge/Sources/Data/Repositories/Project/MockProjectRepository.swift
  Bridge/Sources/Data/Repositories/User/DefaultUserRepository.swift
  Bridge/Sources/Data/Repositories/User/MockUserRepository.swift
  Bridge/Sources/Domain/Entities/Profile/ApplicantProfile.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Project/Applicant/ApplicantRepository.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Project/ProjectRepository.swift
  Bridge/Sources/Domain/RepositoryInterfaces/User/UserRepository.swift
  Bridge/Sources/Domain/UseCases/Project/Applicant/Accept/AcceptApplicantUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Applicant/Apply/ApplyProjectUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Applicant/Cancel/CancelApplicationUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Applicant/List/FetchApplicantListUseCase.swift
  Bridge/Sources/Domain/UseCases/Project/Applicant/Reject/RejectApplicantUseCase.swift
  Bridge/Sources/Domain/UseCases/User/FetchApplicantListUseCase.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/ApplicantListViewModel.swift
  Bridge/Sources/Presentation/Tab/Management/ApplicantList/Cell/ApplicantCell.swift
  Bridge/Sources/Presentation/Tab/Management/Coordinator/ManagementCoordinator.swift
  Bridge/Sources/Presentation/Tab/Management/Management/Cell/ManagementProjectCell.swift
  Bridge/Sources/Presentation/Tab/Management/Management/HeaderView/ManagementHeaderView.swift
  Bridge/Sources/Presentation/Tab/Management/Management/ManagementViewController.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/Coordinator/ProjectDetailCoordinator.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldCell.swift
  Bridge/Sources/Presentation/Tab/ProjectDetail/RecruitFieldDetail/RecruitFieldDetailCell.swift
Labels: feat
