Repository bridge0813/bridge-ios, pull requests merged in 2023-09, with the labels that each got.

#23 테이블 뷰 셀 바인딩
  .gitignore
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/Endpoint/HTTP.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkError.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Chat/DefaultChatRoomRepository.swift
  Bridge/Sources/Data/Repositories/Main/DefaultProjectRepository.swift
  Bridge/Sources/Domain/Entities/Chat/ChatRoom.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Chat/ChatRoomRepository.swift
  Bridge/Sources/Domain/UseCases/Chat/ChatRoom/FetchChatRoomsUseCase.swift
  Bridge/Sources/Domain/UseCases/Main/ObserveProjectsUseCase.swift
  Bridge/Sources/Presentation/Common/Bases/BaseTableViewCell.swift
  Bridge/Sources/Presentation/Common/Bases/BaseView.swift
  Bridge/Sources/Presentation/Common/Bases/BaseViewController.swift
  Bridge/Sources/Presentation/Common/Extensions/UITableView+.swift
  Bridge/Sources/Presentation/Common/Reusable.swift
  Bridge/Sources/Presentation/Common/ViewModelType.swift
  Bridge/Sources/Presentation/Common/Views/NavigationTitleView.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomCell.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
  Bridge/Sources/Presentation/Tab/Coordinator/TabBarCoordinator.swift
  Bridge/Sources/Presentation/Tab/Coordinator/TabBarPageType.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/MainHome/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/MainHome/MainViewModel.swift
  Bridge/Sources/Utils/Date+.swift
Labels: feat

#27 Main 화면 UI구현(Compositional Layout과 DiffableDataSource)
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Main/ProjectDTO.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Domain/Entities/Main/Project.swift
  Bridge/Sources/Domain/UseCases/Main/FetchProjectsUseCase.swift
  Bridge/Sources/Presentation/Common/Bases/BaseCollectionReusableView.swift
  Bridge/Sources/Presentation/Common/Bases/BaseCollectionViewCell.swift
  Bridge/Sources/Presentation/Common/Extensions/UICollectionView+.swift
  Bridge/Sources/Presentation/Common/Extensions/UILabel+.swift
  Bridge/Sources/Presentation/Common/Reusable.swift
  Bridge/Sources/Presentation/Common/Views/ProjectSectionHeaderView.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/Main/HotProjectCollectionViewCell.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/Main/ProjectCollectionViewCell.swift
  Bridge/Sources/Presenter/Tab/Main/Main/HotProjectCollectionViewCell.swift
  Bridge/Sources/Presenter/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presenter/Tab/Main/Main/MainViewModel.swift
  Bridge/Sources/Presenter/Tab/Main/Main/ProjectCollectionViewCell.swift
Labels: feat, design

#28 채팅방 셀 디자인 수정
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomCell.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
Labels: design, chore

#32 채팅방 엔티티 및 셀 수정
  Bridge/Sources/Data/Network/DTOs/Chat/ChatRoomDTO.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Repositories/Chat/DefaultChatRoomRepository.swift
  Bridge/Sources/Domain/Entities/Chat/Chat.swift
  Bridge/Sources/Domain/Entities/Chat/ChatRoom.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomCell.swift
Labels: feat, design

#33 인기 모집글 데이터를 가져오는 로직 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Main/ProjectDTO.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Main/DefaultProjectRepository.swift
  Bridge/Sources/Domain/Entities/Main/Project.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Main/ProjectRepository.swift
  Bridge/Sources/Domain/UseCases/Main/FetchAllProjectsUseCase.swift
  Bridge/Sources/Domain/UseCases/Main/FetchHotProjectsUseCase.swift
  Bridge/Sources/Presentation/Common/Views/ProjectSectionHeaderView.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewModel.swift
Labels: feat

#36 채팅방 목록 뷰 모델, 뷰 컨트롤러 리팩토링
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Domain/Entities/Chat/ChatRoom.swift
  Bridge/Sources/Domain/Entities/Chat/Message.swift
  Bridge/Sources/Presentation/Common/Extensions/UIViewController+Rx.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
Labels: refactor

#39 Main 뷰 플로팅 버튼 구현
  Bridge/Sources/Presentation/Tab/Main/Main/HotProjectCollectionViewCell.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/Main/ProjectCollectionViewCell.swift
Labels: feat, design

#40 채팅방 목록 화면 내비게이션 바 디자인 수정
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Coordinator/TabBarCoordinator.swift
Labels: design

#47 읽지 않은 메시지 개수 레이블 디자인 수정
  Bridge/Sources/Data/Network/DTOs/Chat/ChatRoomDTO.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomCell.swift
Labels: design

#43 Main 뷰 UI 바인딩
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewModel.swift
Labels: feat

#48 채팅방 목록 화면 바인딩 relay로 변경
  .swiftlint.yml
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
Labels: fix

#50 Auth 코디네이터 구현
  Bridge.entitlements
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/App/Coordinator/AppCoordinator.swift
  Bridge/Sources/App/Coordinator/Coordinator.swift
  Bridge/Sources/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewController.swift
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewModel.swift
  Bridge/Sources/Presentation/Auth/SignUp/EnterNameViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
  Bridge/Sources/Presentation/Tab/Coordinator/TabBarCoordinator.swift
Labels: feat

#53 모집글 작성 플로우와 코디네이터
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Presentation/Tab/Main/Coordinator/CreateProjectCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ApplicantRestriction/ApplicantRestrictionViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ApplicantRestriction/ApplicantRestrictionViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/Completion/CompletionViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/Completion/CompletionViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberDetailInput/MemberDetailInputViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberDetailInput/MemberDetailInputViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberFieldSelection/MemberFieldSelectionViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberFieldSelection/MemberFieldSelectionViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectDatePicker/ProjectDatePickerViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectDatePicker/ProjectDatePickerViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectOverviewInput/ProjectDescriptionInputViewModel.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectOverviewInput/ProjectOverviewInputViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectProgressStatus/ProjectProgressStatusViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ProjectProgressStatus/ProjectProgressStatusViewModel.swift
Labels: feat

#57 애플 로그인, 회원가입 구조 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Domain/Entities/Auth/SignInResult.swift
  Bridge/Sources/Domain/Entities/User/UserCredentials.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Auth/AuthRepository.swift
  Bridge/Sources/Domain/UseCases/Auth/CheckUserAuthStateUseCase.swift
  Bridge/Sources/Domain/UseCases/Auth/SignInUseCase.swift
  Bridge/Sources/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewModel.swift
  Bridge/Sources/Presentation/Common/Extensions/ASAuthorizationController+Rx.swift
  Bridge/Sources/Presentation/Common/Views/PlaceholderView.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomCell.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
Labels: feat

#59 채팅방 목록 플레이스홀더 오류 수정 및 리팩토링
  Bridge/Sources/Domain/UseCases/Auth/CheckUserAuthStateUseCase.swift
  Bridge/Sources/Presentation/Common/Views/PlaceholderView.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
Labels: fix, refactor

#61 유저 인증 상태 체크를 위한 도메인, 데이터 레이어 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Domain/Entities/Auth/UserAuthState.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Auth/AuthRepository.swift
  Bridge/Sources/Domain/UseCases/Auth/CheckUserAuthStateUseCase.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
Labels: feat

#65 키체인 저장소 및 로그인 데이터 레이어 구현
  .swiftlint.yml
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Auth/SignInResponseDTO.swift
  Bridge/Sources/Data/Network/DTOs/Auth/SignInWithAppleRequestDTO.swift
  Bridge/Sources/Data/Network/DTOs/Chat/ChatRoomDTO.swift
  Bridge/Sources/Data/Network/Endpoint/AuthEndpoint.swift
  Bridge/Sources/Data/Network/Endpoint/Endpoint.swift
  Bridge/Sources/Data/Network/Endpoint/HTTP.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkError.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Network/TokenStorage/Keychain/KeychainAccount.swift
  Bridge/Sources/Data/Network/TokenStorage/Keychain/KeychainError.swift
  Bridge/Sources/Data/Network/TokenStorage/Keychain/KeychainTokenStroage.swift
  Bridge/Sources/Data/Network/TokenStorage/TokenStorage.swift
  Bridge/Sources/Data/Repositories/Auth/DefaultAuthRepository.swift
  Bridge/Sources/Data/Repositories/Chat/DefaultChatRoomRepository.swift
  Bridge/Sources/Domain/Entities/Auth/SignInResult.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Auth/AuthRepository.swift
  Bridge/Sources/Domain/UseCases/Auth/CheckUserAuthStateUseCase.swift
  Bridge/Sources/Domain/UseCases/Auth/SignInUseCase.swift
  Bridge/Sources/Presentation/Auth/Coordinator/AuthCoordinator.swift
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewController.swift
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewModel.swift
  Bridge/Sources/Presentation/DesignSystem/Foundation/Typography.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presentation/Tab/Chat/Coordinator/ChatCoordinator.swift
Labels: feat

#69 디자인시스템 (Component_Button) 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Presentation/Common/Bases/BaseButton.swift
  Bridge/Sources/Presentation/Common/Buttons/FieldTagButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/BookmarkButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/CancelButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ConfirmButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/FieldTagButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/RemoveButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/SendMessageButton.swift
  Bridge/Sources/Presentation/DesignSystem/Foundation/BridgeFont.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
Labels: design

#72 디자인 시스템(Component)의 Tooltip, Message box 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Presentation/Auth/SignIn/SignInViewController.swift
  Bridge/Sources/Presentation/Auth/SignUp/SelectFieldViewController.swift
  Bridge/Sources/Presentation/Common/Bases/BaseView.swift
  Bridge/Sources/Presentation/DesignSystem/Component/MessageBox/MessageBox.swift
  Bridge/Sources/Presentation/DesignSystem/Component/MessageBox/TipMessageBox.swift
  Bridge/Sources/Presentation/DesignSystem/Component/MessageBox/WarningMessageBox.swift
  Bridge/Sources/Presentation/DesignSystem/Foundation/BridgeColor.swift
  Bridge/Sources/Presentation/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
Labels: feat, design

#73 디자인시스템 Component-Tag 구현 및 Button 리팩토링
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Presentation/Common/Bases/BaseButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/BookmarkButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/BridgeButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ButtonGroup/MediumButtonGroup.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ButtonGroup/SmallButtonGroup.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/CancelButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/ConfirmButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/CreateProjectButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/FieldTagButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/NextButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/OutlinedTagButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/RemoveButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/SendMessageButton.swift
  Bridge/Sources/Presentation/DesignSystem/Component/Buttons/TagButton.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/ApplicantRestriction/ApplicantRestrictionViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberDetailInput/MemberRequirementInputViewController.swift
  Bridge/Sources/Presentation/Tab/Main/CreateProject/MemberFieldSelection/MemberFieldSelectionViewController.swift
  Bridge/Sources/Presentation/Tab/Main/Main/MainViewController.swift
Labels: design
