Repository bridge0813/bridge-ios, pull requests merged in 2023-08, with the labels that each got.

#5 코디네이터 패턴 도입
  .DS_Store
  Bridge.xcodeproj/project.pbxproj
  Bridge/.DS_Store
  Bridge/App/SceneDelegate.swift
  Bridge/Sources/App/AppCoordinator.swift
  Bridge/Sources/App/AppDelegate.swift
  Bridge/Sources/App/Coordinator.swift
  Bridge/Sources/App/SceneDelegate.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presenter/Tab/Chat/Coordinator/ChatCoordinator.swift
  Bridge/Sources/Presenter/Tab/Coordinator/TabBarCoordinator.swift
  Bridge/Sources/Presenter/Tab/Coordinator/TabBarPageType.swift
  Bridge/ViewController.swift
Labels: feat

#8 MainCoordinator 생성
  .DS_Store
  Bridge.xcodeproj/project.pbxproj
  Bridge.xcodeproj/project.xcworkspace/xcuserdata/eomjiho.xcuserdatad/UserInterfaceState.xcuserstate
  Bridge/Sources/Presenter/Tab/Coordinator/TabBarCoordinator.swift
  Bridge/Sources/Presenter/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presenter/Tab/Main/MainHome/MainViewController.swift
Labels: feat

#9 채팅방 목록 화면의 클린 아키텍처 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Sources/Data/Network/DTOs/Chat/ChatRoomDTO.swift
  Bridge/Sources/Data/Network/Endpoint/Endpoint.swift
  Bridge/Sources/Data/Network/Endpoint/HTTP.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkError.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Chat/DefaultChatRoomRepository.swift
  Bridge/Sources/Domain/Entities/Chat/Chat.swift
  Bridge/Sources/Domain/Entities/Chat/ChatRoom.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Chat/ChatRoomRepository.swift
  Bridge/Sources/Domain/UseCases/Chat/ChatRoom/LeaveChatRoomUseCase.swift
  Bridge/Sources/Domain/UseCases/Chat/ChatRoom/ObserveChatRoomsUseCase.swift
  Bridge/Sources/Presenter/Common/ViewModelType.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presenter/Tab/Chat/Coordinator/ChatCoordinator.swift
Labels: feat

#12 프로젝트 파일 충돌 문제 해결
  .DS_Store
  Bridge.xcodeproj/project.pbxproj
  Bridge.xcodeproj/project.xcworkspace/xcuserdata/junghoyun.xcuserdatad/xcschemes/xcschememanagement.plist
  Bridge/Sources/Domain/Entities/Chat/ChatRoom.swift
  Bridge/Sources/Presenter/Common/Base/BaseTableViewCell.swift
  Bridge/Sources/Presenter/Common/Base/BaseViewController.swift
  Bridge/Sources/Presenter/Common/Extensions/UITableView+.swift
  Bridge/Sources/Presenter/Common/Reusable.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomTableViewCell.swift
Labels: fix

#19 Main 화면의 Clean Architecture 구현
  .DS_Store
  Bridge.xcodeproj/project.pbxproj
  Bridge.xcodeproj/project.xcworkspace/xcuserdata/eomjiho.xcuserdatad/UserInterfaceState.xcuserstate
  Bridge/Sources/Data/Network/DTOs/Main/ProjectDTO.swift
  Bridge/Sources/Data/Network/NetworkService/DefaultNetworkService.swift
  Bridge/Sources/Data/Network/NetworkService/NetworkService.swift
  Bridge/Sources/Data/Repositories/Main/DefaultProjectRepository.swift
  Bridge/Sources/Domain/Entities/Main/Project.swift
  Bridge/Sources/Domain/RepositoryInterfaces/Main/ProjectRepository.swift
  Bridge/Sources/Domain/UseCases/Main/ObserveProjectsUseCase.swift
  Bridge/Sources/Extension/Date+Utilities.swift
  Bridge/Sources/Presenter/Tab/Main/Coordinator/MainCoordinator.swift
  Bridge/Sources/Presenter/Tab/Main/MainHome/MainViewController.swift
  Bridge/Sources/Presenter/Tab/Main/MainHome/MainViewModel.swift
Labels: feat

#20 채팅방 목록 뷰 구현
  Bridge.xcodeproj/project.pbxproj
  Bridge/Resources/Info.plist
  Bridge/Sources/Presenter/Common/Bases/BaseTableViewCell.swift
  Bridge/Sources/Presenter/Common/Bases/BaseView.swift
  Bridge/Sources/Presenter/Common/Bases/BaseViewController.swift
  Bridge/Sources/Presenter/Common/Views/NavigationTitleView.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomCell.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewController.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomListViewModel.swift
  Bridge/Sources/Presenter/Tab/Chat/ChatRoomList/ChatRoomTableViewCell.swift
  Bridge/Sources/Presenter/Tab/Coordinator/TabBarCoordinator.swift
Labels: feat, design
